sonar.projectKey=hilfe-v2-backend
sonar.projectName=Hilfe v2 Backend
sonar.projectVersion=2.0
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.exclusions=**/target/**,**/*.xml,**/generated-sources/**
sonar.host.url=https://sonar-qube.amalitech-dev.net
