sonar.projectKey=hilfe-v2-backend
sonar.projectName=Hilfe v2 Backend
sonar.projectVersion=2.0
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.test.inclusions=**/*Test.java,**/*Tests.java,**/*IT.java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.exclusions=**/target/**,**/generated-sources/**,src/test/**,src/main/resources/templates/email/**
sonar.coverage.exclusions=**/dto/**,**/models/**,**/exceptions/**,**/config/**,**/HilfeApplication.java
sonar.host.url=https://sonar-qube.amalitech-dev.net
