-- INSERT INTO "Status" (id, name, description, show_on_reply, created_at, updated_at)
-- VALUES
--     ('status-open',        'Open',        'Incident has been submitted and is awaiting action', true,  NOW(), NOW()),
--     ('status-in-progress', 'Pending', 'Incident is actively being worked on',               true,  NOW(), NOW()),
--     ('status-pending',     'Resolved',     'Incident is waiting on additional information',       true,  NOW(), NOW()),
--     ('status-closed',      'Closed',      'Incident has been resolved and closed',               false, NOW(), NOW())
-- ON CONFLICT (id) DO NOTHING;
